INSERT INTO menuitems (keyingredient_id, name, ingredients, price, image) VALUES (1, 'Chicken Parmesan','boneless chicken breast, eggs, parmesan cheese', 11.99, 'https://www.cookingclassy.com/wp-content/uploads/2013/02/chicken-parmesan-16.jpg');
INSERT INTO menuitems (keyingredient_id, name, ingredients, price, image) VALUES (1, 'Chicken Marsala','boneless chicken breast, cayenne pepper, egg', 12.99, 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.thechunkychef.com%2Fwp-content%2Fuploads%2F2016%2F04%2FEasy-Chicken-Marsala-9.jpg&f=1&nofb=1');
INSERT INTO menuitems (keyingredient_id, name, ingredients, price, image) VALUES (2, 'Rice Noodle Salad','rice noodles, romaine lettuce, red bell pepper, onions',13.99, 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.thespruceeats.com%2Fthmb%2FC9nkoRZYQQjw6Mrk8FY6nqhORdk%3D%2F1500x1000%2Ffilters%3Afill(auto%2C1)%2Frice-noodle-salad-chili-lime-vinaigrette-3217646-11copy-5b3f91e546e0fb003755482d.jpg&f=1&nofb=1');
INSERT INTO menuitems (keyingredient_id, name, ingredients, price, image) VALUES (2, 'Veggie Pasta', 'noodles, mushrooms, basil, cherry tomatoes, heavy cream', 11.99, 'https://www.simplyscratch.com/wp-content/uploads/2014/03/Roasted-Vegetable-Pasta-Primavera-www.SimplyScratch.com-salt-pepper-and-toss.jpg');
INSERT INTO menuitems (keyingredient_id, name, ingredients, price, image) VALUES (3, 'Nachos','tortilla  chips, black beans, sour cream, cheese' ,4.99, 'https://assets.rebelmouse.io/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vd3d3LmF2ZXJpZWNvb2tzLmNvbS93cC1jb250ZW50L3VwbG9hZHMvMjAxOS8wMS9iZWVmbmFjaG9zLTUuanBnIiwiZXhwaXJlc19hdCI6MTYyMzA0MjIwNX0.ekevNVe2VrWfPZBME5M3qp-_bkQN24cOvABbE1dEOwQ/img.jpg?width=2000&height=2000');
INSERT INTO menuitems (keyingredient_id, name, ingredients, price, image) VALUES (3, 'Fries', 'potatoes, salt, truffle oil', 5.99, 'https://www.delonghi.com/Global/recipes/multifry/91.jpg');
INSERT INTO menuitems (keyingredient_id, name, ingredients, price, image) VALUES (4, 'Lemon Loaf','butter, sugar, eggs, flour' 3.99, 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.seasonsandsuppers.ca%2Fwp-content%2Fuploads%2F2017%2F05%2Flemon-loaf800E-1170x780.jpg&f=1&nofb=1');
INSERT INTO menuitems (keyingredient_id, name, ingredients, price, image) VALUES (4, 'Cinnamon Rolls', 'milk, eggs, margarine, flour, white sugar, yeast' 4.99, 'https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F43%2F2020%2F04%2F08%2FClone-of-a-Cinnabon-by-abrooks-2000.jpg&w=426&h=285&c=sc&poi=face&q=60');
INSERT INTO menuitems (keyingredient_id, name, ingredients, price, image) VALUES (5, 'Bottled Water', 'Spring Water' 1.99, 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpurepng.com%2Fpublic%2Fuploads%2Flarge%2Fpurepng.com-ice-water-bottle-aquafinabottle-water-drink-aquafina-9415246348499t1u0.png&f=1&nofb=1');
INSERT INTO menuitems (keyingredient_id, name, ingredients, price, image) VALUES (5,'Coca-Cola', NULL, 0.99, 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.scoopsofmalton.co.uk%2Fwp-content%2Fuploads%2F2020%2F05%2Fcoca-cola.jpg&f=1&nofb=1');



